server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: hello-service
          uri: lb://hello-service
          predicates:
            - Path=/hello/**
        - id: goodbye-service
          uri: lb://goodbye-service
          predicates:
            - Path=/goodbye/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 